global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:3000']

  - job_name: 'cdc-consumer'
    metrics_path: /metrics
    static_configs:
      - targets: ['cdc-consumer:9100']
